# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        Dialog.setMinimumSize(QtCore.QSize(400, 200))
        Dialog.setMaximumSize(QtCore.QSize(400, 200))
        Dialog.setSizeIncrement(QtCore.QSize(0, 0))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.but_yes = QtWidgets.QPushButton(Dialog)
        self.but_yes.setGeometry(QtCore.QRect(50, 120, 130, 50))
        self.but_yes.setMinimumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_yes.setFont(font)
        self.but_yes.setStyleSheet("color: rgb(255, 0, 0);")
        self.but_yes.setObjectName("but_yes")
        self.but_no = QtWidgets.QPushButton(Dialog)
        self.but_no.setGeometry(QtCore.QRect(220, 120, 130, 50))
        self.but_no.setMinimumSize(QtCore.QSize(130, 50))
        self.but_no.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.but_no.setObjectName("but_no")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Bạn muốn thoát chương trình?"))
        self.but_yes.setText(_translate("Dialog", "Có"))
        self.but_no.setText(_translate("Dialog", "Không"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
